//LOCALHOST

###GET ALL
GET http://localhost:3000/users

###GET BY ID
GET http://localhost:3000/users/67cc507cc8ebbc8ac1af6ba8

###CREATE USER
POST http://localhost:3000/users HTTP/1.1
content-type: application/json

{
    "firstName": "Chris",
    "lastName": "Topher",
    "email": "christopher@email.com",
    "favoriteColor": "Baby Blue",
    "birthday": "01/02/1999"
}

###UPDATE USER
PUT http://localhost:3000/users/67d3563dcb579c0fd974d0b4 HTTP/1.1
content-type: application/json

{
    "firstName": "Talia",
    "lastName": "Richter",
    "email": "talia.richter@mail.test",
    "favoriteColor": "Red",
    "birthday": "04/04/2000"
}

###DELETE USER
DELETE http://localhost:3000/users/67d3560fcb579c0fd974d0b3 HTTP/1.1